events { worker_connections 4; }

http {
	server {
		listen 443 ssl;
		ssl_certificate /etc/nginx/site.crt;
		ssl_certificate_key /etc/nginx/site.key;
		ssl_protocols TLSv1.2 TLSv1.3;
		
		location / {
			proxy_pass http://whoami:80;
		}
	}
}
